### ISSUE TITLE
validation succeded by typeError in console

### ISSUE THREAD

**Issue by FabrizioReitano** [FriendlyCaptcha/friendly-challenge#162]
Hi,
in my local development environment, i created a web page with the widget pointing the "puzzle endpoint" to my local instance of the "friendly-lite-server". The verification succed but if i look at the console i can see this error:

`widget.module.min.js:1 Uncaught TypeError: window[r] is not a function
    at workerGroup.doneCallback (widget.module.min.js:1:24374)
    at workers.<computed>.onmessage (widget.module.min.js:1:18359)
workerGroup.doneCallback @ widget.module.min.js:1
workers.<computed>.onmessage @ widget.module.min.js:1`

Am i missing someting? That's my HTML page:

```
<!DOCTYPE html>
<html lang="en"> 
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script type="module" src="https://unpkg.com/friendly-challenge@0.9.8/widget.module.min.js" async defer></script>
        <script nomodule src="https://unpkg.com/friendly-challenge@0.9.8/widget.min.js" async defer></script>
        <title>Friendly Captcha form</title>
    </head>
    <body>
        <div class="container mt-5">
            <h1>FriendlyCaptcha Demo</h1>
            <form>
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input type="email" class="form-control" id="username" aria-describedby="usernameHelp">
                  <div id="usernameHelp" class="form-text">Your username</div>
                </div>
                <div class="frc-captcha mt-5" data-sitekey="j2DXnqsfGn" data-callback="myCallback" data-lang="it" data-puzzle-endpoint="http://localhost:8088/puzzle.php"></div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>
```

**Comment by gzuidhof** [comment]
You have set a `data-callback` value, it looks for a function that is available in the global scope (e.g. a function that is on the window object) called `myCallback`.

So you could create such a function, or remove it. The function could look something like this:

```javascript
window["myCallback"] = function() { console.log("Captcha completed! 🎉" }
```
